apiVersion: apps/v1
kind: Deployment
metadata:
  name: axion-ingestion-service
spec:
  selector:
    matchLabels:
      app: axion-ingestion-service
  template:
    metadata:
      labels:
        app: axion-ingestion-service
    spec:
      containers:
      - name: axion-ingestion-service
        image: acrmicrodev567.azurecr.io/axion-ingestion-service:v1
        ports:
        - containerPort: 8000
