apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 6
  selector:
    matchLabels:
      brand: gucci
  template:
    metadata:
      labels:
        brand: gucci
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80