apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: dimple-pvc
spec: 
  storageClassName: ""
  accessModes:
  - ReadWriteMany
  resources:
    requests: 
      storage: 100Gi
  volumeName: dimple-website-storage-pv