apiVersion: v1
kind: Secret
metadata:
  name: azure-secret
  namespace: default
type: Opaque
stringData:
  azurestorageaccountname: netfliixstoraage
  azurestorageaccountkey: lJpJ6/i6qYuXQ43YJptJSGaIlF0Mu4jQT+ud+V1r7Fz3hKNR+7gHuQ17G0NG/9k69nkzzv4UASEi+AStchDB7A==